/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 8 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"

/* void esborraBit(){
   // copiabit
   
}
*/

/* copiaBitAltrePort(){
   int f = 0x01;
      for(f = 0; f < j; ++f){
	 f << 1;
    }
}
*/



int e = 0;
int i = 0;
int j = 0;

void colocaBitAlt(){
   if(i == 1){
      PORTC = PORTD;
      PORTD = 0;
   }
   else if(i == 0){
      PORTB = PORTC;
      PORTC = 0;
   }
   return;
}

void colocaBitBaix(){
   if(i == 1){
      PORTC = PORTB;
      PORTB = 0;
   }
   else if(i == 2){
      PORTD = PORTC;
      PORTC = 0;
   }
   return;
}

void colocaBitDret(){
   if(i == 0){
      PORTB = PORTB >> 1;
   }
   else if(i == 1){
      PORTC = PORTC >> 1;
   }
   else if(i == 2){
      PORTD = PORTD >> 1;
   }
   return;
}

void colocaBitEsq(){
   if(i == 0){
      PORTB = PORTB << 1;
   }
   else if(i == 1){
      PORTC = PORTC << 1;
   }
   else if(i == 2){
      PORTD = PORTD << 1;
   }
   return;
}



void main(void){
   ANSELA = 0; // All pins as digital
   ANSELB = 0x00;
   ANSELC= 0x00;
   ANSELD= 0;
   ANSELE= 0;
   TRISA = 0x1F; // 0000 1111
   TRISB = 0x00; // 
   TRISC = 0x00; // Tot TRISC = output
   TRISD = 0;
   TRISE = 0;
   PORTA = 0;
   PORTC = 0;
   PORTD = 0;
   PORTE = 0;
   PORTB = 1;
   int b = 0; // RA1
   int c = 0; // RA3
   int d = 0; // RA4
   while(1) {
      if(PORTAbits.RA1 == 1 && b == 0){
	 j = j - 1;
	 b = 1;
	 colocaBitEsq();
      }
      if(PORTAbits.RA1 == 0 && b == 1){
	 b = 0;
      }
      if(PORTAbits.RA3 == 1 && c == 0){
	 j = j + 1;
	 c = 1;
	 colocaBitDret();
      }
      
      if(PORTAbits.RA3 == 0 && c == 1){
	 c = 0;
      }
      if(PORTAbits.RA2 == 1 && d == 0){
	 i = i + 1;
	 d = 1;
	 colocaBitBaix();
      }
      if(PORTAbits.RA2 == 0 && d == 1){
	 d = 0;
      }
      if(PORTAbits.RA0 == 1 && e == 0){
	 i = i - 1;
	 e = 1;
	 colocaBitAlt();
      }
      if(PORTAbits.RA0 == 0 && e == 1){
	 e = 0;
      }
      
      /*
      if(PORTAbits.RA1 == 1 && b == 0){
	 PORTB = << 1;
	 b = 1;
      }
      if(PORTBbits.RA1 == 0 && b == 1){
	 b = 0;
      }
      if(PORTAbits.RA3 == 1 && c == 0){
	 PORTB = >> 1;
	 c = 1;
      }
      if(PORTAbits.RA3 == 0 && c == 1){
	 c = 0;
      }
      if(PORTAbits.RA2 == 1 && d == 0 && bajaRC == 0){
	 PORTC = PORTB;
	 PORTB = 0;
	 bajaRC = 1;
	 d = 1;
      }
      if(PORTAbits.RA2 == 0 && d == 1){
	 d = 0;
      }
      if(PORTAbits.RA2 == 1 &&)
      */
   }
}