/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 8 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"
#define _XTAL_FREQ 8000000

/* void esborraBit(){
   // copiabit
   
}
*/

/* copiaBitAltrePort(){
   int f = 0x01;
      for(f = 0; f < j; ++f){
	 f << 1;
    }
}
*/



void main(void){
   ANSELA = 0; // All pins as digital
   ANSELB = 0x00;
   ANSELC= 0x00;
   ANSELD= 0;
   ANSELE= 0;
   TRISA = 0x00; // 0000 1111
   TRISB = 0x00; // 
   TRISC = 0x00; // Tot TRISC = output
   TRISD = 0;
   TRISE = 0;
   PORTA = 0;
   PORTC = 0;
   PORTD = 0;
   PORTE = 0;
   PORTB = 0;
   int b = 0; // RA1
   int c = 0; // RA3
   int d = 0; // RA4
   while(1) {
      PORTA = 0xFF;
      PORTB = 0x80;
      PORTC = 0x80;
      PORTD = 0xFF;
      
      __delay_ms(500);
      
      PORTA = 0xFF;
      PORTB = 0x08;
      PORTC = 0x08;
      PORTD = 0xFF;
      
      __delay_ms(500);
      __delay_ms(500);
      
      PORTA = 0x80;
      PORTB = 0x80;
      PORTC = 0x80;
      PORTD = 0xFF;
      
      __delay_ms(500);
      
      PORTA = 0x18;
      PORTB = 0x24;
      PORTC = 0x42;
      PORTD = 0x81;
      
      __delay_ms(500);
      
      PORTA = 0xF8;
      PORTB = 0xC9;
      PORTC = 0xC9;
      PORTD = 0xF8;
      
      __delay_ms(500);
   }
}