;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   lu. oct. 2 2023
; Processor: PIC18F45K22
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p18f45k22.inc
config FOSC = HSHP
;========================================================
; VARIABLES
;========================================================
var1 equ 0x20
del equ 0x0D
;========================================================
; RESET and INTERRUPT VECTORS
;========================================================
RST code 0x0
goto Start
;=================
;=======================================
; CODE SEGMENT
;========================================================
PGM code
Start
   movlw B'00000001'; W=0
   ; Configurar PORTs
   movlb 0xF		; Preparar BSRs per als banked SFRs
   clrf PORTB, 1	; Borrar PORTB
   clrf LATB,1		; Mètode altern per a borrar l'output
   movlw 0xF8		; W = (0b 1111 1110)
   movwf ANSELB, 1	; Sel·leccionar RB0, RB1 i RB2 com a digitals
   movlw 0xF9		;  W = (0b 1111 1001)
   movwf TRISB, 1	; Sel·leccionar RB0 com a input i RB1, RB2 com a output (RB3..RB7 com a input, però no els utilitzarem)
Loop
   ; Llegir RB0 i actualitzar RB1
   btfss PORTB, 0, 1	; si al bit 0 de PORTB hi ha un 1, se salta la següent instrucció (if RB0 == 1 --> skip next)
   bsf LATB, 1, 1	; posar un 1 al bit 1 del RB (RB1 = 1)
   btfsc PORTB, 0, 1	; si al bit 0 de PORTB hi ha un 0, se salta la següent instrucció (if RB0 == 0 --> skip next)
   bcf LATB, 1, 1	; posar un 0 al bit 1 del RB (RB1 = 0)
   goto Loop
   
   

;====================================================================
      END
