/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 26 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include <stdlib.h>
#include <time.h>
#include "config.h"
#define _XTAL_FREQ 8000000

int count = 1;
int randGen = 0;
int digit = 0;
int init1and2 = 0;

// Dígits del nombre a representar
char num[4];

// El num de la pos. del vector, es correspon al valor contingut en aquesta, per representar-ho al led
char transform[] = {0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x67};

void setNumber(int aux){
   if(aux > 9999){
      digit = 9999;
      aux = digit;
   }
   for(int i = 3; i >= 0; --i){
	 num[i] = aux % 10;
	 aux = aux / 10;
   }
}

// Col·loca a vector num, un nombre pseudoaleatori entre 0 i 9999, a partir del nombre seed
void setRandomNumber(){
   // Generació de nombre aleatori
      srand(randGen);
      digit = rand() % 9999; // rang del nombre aleatori [0, 9999]
      setNumber(digit);
}

void mostrarNum(){
   int desp = 0;
   int selec = 0x08;
   for (int i = 0; i < 4; ++i){
      PORTA = selec;
      PORTD = transform[num[i]];
      __delay_ms(2);
      selec = selec >> 1;
   }
}


void interrupt service_routine_HP(void){
   if(INTCONbits.INT0IF && INTCONbits.INT0IE){
      INTCONbits.INT0IF = 0;
      setRandomNumber();
      if(init1and2 == 0){ // Preparar les interrupcions INT1 INT2, la primera vegada que s'activa la interrupció INT0
	 // Enable bits
	 INTCON3bits.INT1E = 1;
	 INTCON3bits.INT2IE = 1;
	 // Init flags
	 INTCON3bits.INT1IF = 0;
	 INTCON3bits.INT2IF = 0;
	 // Escollir si reaccionen als flangs ascendents o descendents
	 INTCON2bits.INTEDG1 = 0;
	 INTCON2bits.INTEDG1 = 1;
	 init1and2 = 1;
      }
   }
   if(INTCON3bits.INT1F && INTCON3bits.INT1IE){
      INTCON3bits.INT1F = 0;
      digit += count;
      setNumber(digit);
   }
   if(INTCON3bits.INT2F && INTCON3bits.INT2IE){
      INTCON3bits.INT2F = 0;
      if(count < 1000){
	 count *= 10;
      }
      else{
	 count = 1;
      }
   }
}

void main(void){
   ANSELA = 0; // All pins as digital
   ANSELB = 0x00;
   ANSELC= 0x00;
   ANSELD= 0;
   ANSELE= 0;
   TRISA = 0x00; // Tot TRISA = output
   TRISD = 0x00; // Tot TRISD = output
   PORTA = 0;
   PORTD = 0;
   
   // Inicialitzar INT0
   INTCONbits.GIEH = 1; // Global enable bits
   INTCONbits.INT0IE = 1; // Enable bits
   INTCONbits.INT0IF = 0; // External interrupt flag off
   INTCON2bits.INTEDG0 = 1; // Interrupt on rising edge (flang ascendent)
   
   while(1) {
      mostrarNum();
      ++randGen;
   }
}