/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 14 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include <stdlib.h>
#include <time.h>
#include "config.h"
#define _XTAL_FREQ 8000000

const unsigned char mapping[]= {

/*  space !     "     #     $     %     &     '     (     )     *     +     */

    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x39, 0x0F, 0x00, 0x00,

/*  ,     -     .     /                                                     */

    0x04, 0x40, 0x80, 0x00,

/*  0     1     2     3     4     5     6     7     8     9     :     ;     */

    0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 0x7F, 0x6F, 0x00, 0x00, 

/*  <     =     >     ?     @     A     B     C     D     E     F     G     */

    0x00, 0x48, 0x00, 0xD3, 0x00, 0x77, 0x7C, 0x39, 0x5E, 0x79, 0x71, 0x3D, 

/*  H     I     J     K     L     M     N     O     P     Q     R     S     */

    0x76, 0x30, 0x1E, 0x76, 0x38, 0x76, 0x54, 0x3F, 0x73, 0x67, 0x50, 0x6D, 

/*  T     U     V     W     X     Y     Z     [     \     ]     ^     _     */

    0x78, 0x3E, 0x3E, 0x3E, 0x76, 0x6E, 0x5B, 0x39, 0x00, 0x0F, 0x00, 0x08, 

/*  '     a     b     c     d     e     f     g     h     i     j     k     */

    0x00, 0x77, 0x7C, 0x58, 0x5E, 0x79, 0x71, 0x3D, 0x74, 0x30, 0x1E, 0x76, 

/*  l     m     n     o     p     q     r     s     t     u     v     w     */

    0x30, 0x76, 0x54, 0x5C, 0x73, 0x67, 0x50, 0x6D, 0x78, 0x1C, 0x3E, 0x3E, 

/*  x     y     z     */

    0x76, 0x6E, 0x5B

};

char frase[4]; // Serà l'output

void mostraFrase(){
   int selec = 0x08;
   for(int i = 0; i < 4; ++i){
      PORTA = selec;
      PORTD = frase[i];
      __delay_ms(2);
      selec = selec >> 1;
   }
}



void transformaOutput(char *lletres){
   for(int i = 0; i < 4; ++i){
      if(lletres[i] == '\0'){
	 frase[i] = 0x00; // Si es troba amb el final de l'string, perquè s'apagui el led, l'assignem el valor corresponent a space
      }
      else{
	frase[i] = mapping[lletres[i] - 32]; 
      }
   }
}



void main(void){
   ANSELA = 0; // All pins as digital
   ANSELB = 0x00;
   ANSELC= 0x00;
   ANSELD= 0;
   ANSELE= 0;
   TRISA = 0x00; // Tot TRISA = output
   TRISC = 0xFF; // Tot TRISC = input
   TRISD = 0x00; // Tot TRISD = output
   PORTA = 0;
   PORTC = 0;
   PORTD = 0;
   int count = 0;
   char lletres[] = "CI LAB 3";
      while(1){
	 for(int i = 0; lletres[i] != '\0'; ++i){
	    transformaOutput(&lletres[i]);
	    while(count < 50){
	       mostraFrase();
	       ++count;
	    }
	    count = 0;
	    mostraFrase();
	    __delay_ms(2);
	    if(lletres[i] == '\0'){
	       i = 0;
	    }
	 }
      }
}