/* Main.c file generated by New Project wizard
 *
 * Created:   do. oct. 8 2023
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"

void main(void){
   ANSELA = 0; // All pins as digital
   ANSELB = 0x00;
   ANSELC= 0x00;
   ANSELD= 0;
   ANSELE= 0;
   TRISA = 0;
   TRISB = 0xFD; // Tot TRISB = output, excepte RB1
   TRISC = 0x00; // Tot TRISC = output
   TRISD = 0;
   TRISE = 0;
   PORTB = 0;
   PORTC = 0;
   int b = 0;
   int c = 0;
   while(1) {
      PORTBbits.RB1 = !PORTBbits.RB0;
      if(PORTBbits.RB2 == 1 && b == 0){
	 ++PORTC;
	 b = 1;
      }
      if(PORTBbits.RB2 == 0 && b == 1){
	 b = 0;
      }
      if(PORTBbits.RB3 == 1 && c == 0){
	 c = 1;
      }
      if(PORTBbits.RB3 == 0 && c == 1){
	 PORTC = 0;
	 c = 0;
      }
   }
}